In [1]:
from sklearn import linear_model
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('homeprices.csv')

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [15]:
# nan value fiil

import math
df.bedrooms.median()

4.0

In [16]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [18]:
model = linear_model.LinearRegression()
model.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [19]:
model.predict([[3000,3,40]])

C:\Users\Pratap\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [20]:
model.predict([[3000,3,10]])

C:\Users\Pratap\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([595359.7888393])

In [23]:
print(model.coef_)
print(model.intercept_)

[  112.06244194 23388.88007794 -3231.71790863]
221323.00186540384


In [24]:
model.predict([[2500,4,5]])

C:\Users\Pratap\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [25]:
# practice

In [56]:
from sklearn import linear_model
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [57]:
df = pd.read_csv('hiring.csv')

In [58]:
df

experience  test_score  interview_score  salary
0           1         8.0                9   50000
1           4         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [59]:
import math
df.test_score.median()


8.0

In [60]:
df.test_score = df.test_score.fillna(df.test_score.median())

In [61]:
df

experience  test_score  interview_score  salary
0           1         8.0                9   50000
1           4         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [62]:
new_df = df.drop('salary',axis='columns')

In [63]:
new_df

experience  test_score  interview_score
0           1         8.0                9
1           4         8.0                6
2           5         6.0                7
3           2        10.0               10
4           7         9.0                6
5           3         7.0               10
6          10         8.0                7
7          11         7.0                8

In [64]:
model = linear_model.LinearRegression()
model.fit(new_df,df.salary)

LinearRegression()

In [65]:
model.predict([[2,9,6]])

C:\Users\Pratap\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([46445.07623773])

In [66]:
model.predict([[12,10,10]])

C:\Users\Pratap\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([97477.59950744])

In [67]:
model.score(new_df,df.salary)

0.856209215768624